### ISSUE TITLE
Network Configuration Using cloud-init

### ISSUE THREAD

**Issue by j-petit** [hetznercloud/cli#297]
Hi,
I am trying to do network interface configuration via `cloud-init` and `hcloud` like
```
hcloud server create --name private-client-3 --type cx11 --image ubuntu-20.04 --user-data-from-file test.yml
```
where the `test.yml` is
```
#cloud-config

network:
  version: 2
  ethernets:
    ens10:
      dhcp4: true
      gateway4: 10.253.0.1
      nameservers:
        addresses: [8.8.8.8]

final_message: "The system is finally up"
```
However, the system seems not to be configured correctly - the content of `/etc/netplan/50-cloud-init.yaml` is still
```
network:
    version: 2
    ethernets:
        eth0:
            addresses:
            - 2a01:4f8:1c1c:2d81::1/64
            dhcp4: true
            gateway6: fe80::1
            match:
                macaddress: 96:00:00:96:1c:33
            set-name: eth0
```
which does not correspond to my desired configuration. Do you have any ideas what could be the problem that my user-data is not applied? `cloud-init status --long` reports no errors
```
status: done
time: Thu, 11 Feb 2021 09:20:46 +0000
detail:
DataSourceHetzner
```
