### ISSUE TITLE
fix: integer fields are displayed as floats when using `describe` with `o=yaml`

### ISSUE THREAD

**Issue by pauhull** [hetznercloud/cli#638]
When outputting resources in YAML format using `describe`, some integer fields (like IDs) are interpreted as floating point numbers and are thus unusable. Example output of `$ hcloud image describe fedora-39 -o=yaml`:
```yaml
architecture: x86
bound_to: null
created: 2023-11-09T06:19:32+00:00
created_from: null
deleted: null
deprecated: null
description: Fedora 39
disk_size: 5.0
id: 1.35075974e+08 # interpreted as floating point
image_size: null
labels: {}
name: fedora-39
os_flavor: fedora
os_version: "39"
protection:
  delete: false
rapid_deploy: true
status: available
type: system
```

This is because when running `describe`, the API response is decoded into a `map[string]any`. The Go `json` library defaults to `float64` when converting JSON number literals into an `any`, so in the encoding back to YAML these integer fields are interpreted as floats.
